### ISSUE TITLE
Hover effect on buttons

### ISSUE THREAD

**Issue by ashfahan** [assemblysoft/charity-template#1]
https://assemblysoft.github.io/charity-template/Homepage%207%20-%20Image%20Text%20%20Split.html

By default all buttons used in the template have default hover effect applied on them (darken the background color).

do we need to change it ?

**Comment by assemblysoft** [comment]
https://assemblysoft.github.io/charity-template/Homepage%202%20-%20Full%20screen%20image%20split%20text.html

Buttons:
Register Now
Order your noses for your school

Cannot see the hover effect.

**Comment by ashfahan** [comment]
yes you are right it is not that much prominent. That is default bootstrap dark button should it make it mode darker on hover ? what do you think. else we need go in deep customization and change the behavior of default bootstrap buttons.

![Screenshot 2020-12-21 002011](https://user-images.githubusercontent.com/19289015/102722434-e5e6f680-4322-11eb-9886-ed27bf90d607.png)

**Comment by assemblysoft** [comment]
The final colors used for the entire site will be more Green/Yellow/Brown
to fit in with Big cats in the wild + rainforest conservation.
Maybe you can try with some more relevant color schemes. Black for the
buttons is not needed. With a change in colors, you may be able to see the
bootstrap hover effect better?


Carl Randall

telephone: +44 (0)1202 428719

mobile: +44 (0)7782 341372

web: assemblysoft.com

email: carl@assemblysoft.com


This message is a private communication. It may contain information that is
privileged or confidential.

If you are not the intended recipient please do not read, copy or use it,
and do not disclose it to others.

Please notify the sender of the delivery error by replying to this message,
and then delete it and any attachments from your system.

Thank you.

Assemblysoft Ltd

Registered in England & Wales. Company No.07098083
<https://beta.companieshouse.gov.uk/>

Registered Office: 2 Woodland Walk, Bournemouth, Dorset, BH5 1LU

**Comment by ashfahan** [comment]
lets deal with color schemes at the end of the designing phase . first lets get the basic Skelton up and then after putting the content we and futher tweak the design and coloring of the template. because at that time it will easier for us to pick which color to use or not to use

**Comment by assemblysoft** [comment]
Sounds good.
