### ISSUE TITLE
Header Tabs Do not look nice on clicked state

### ISSUE THREAD

**Issue by assemblysoft** [assemblysoft/charity-template#10]

**Comment by assemblysoft** [comment]
This does not look nice. Looks offset, not in a good way.

Please find an alternative solution for the clicked border state.

![image](https://user-images.githubusercontent.com/1641755/105168267-ce618000-5b11-11eb-8516-9251f72a03b5.png)

**Comment by ashfahan** [comment]
![image](https://user-images.githubusercontent.com/19289015/106335514-cee6dd00-62ae-11eb-88b9-441e29803d35.png)
