### ISSUE TITLE
Footer columns should be centered

### ISSUE THREAD

**Issue by assemblysoft** [assemblysoft/charity-template#12]

**Comment by assemblysoft** [comment]
![image](https://user-images.githubusercontent.com/1641755/105169070-e5ed3880-5b12-11eb-8169-f11d33d3a4de.png)

**Comment by ashfahan** [comment]
![image](https://user-images.githubusercontent.com/19289015/105644100-8ba6fb80-5eb5-11eb-8871-445e5f0e31f9.png)
