### ISSUE TITLE
Homepage 2 - Full screen split - down arrow not visible in viewport

### ISSUE THREAD

**Issue by assemblysoft** [assemblysoft/charity-template#18]

**Comment by assemblysoft** [comment]
Down arrow should show within first view of landing page. Need to scroll down to see. Which is incorrect.

![image](https://user-images.githubusercontent.com/1641755/105171752-7f6a1980-5b16-11eb-8bdb-6cd3ae300ace.png)

**Comment by ashfahan** [comment]
![Uploading image.png…]()

**Comment by ashfahan** [comment]
![image](https://user-images.githubusercontent.com/19289015/105643012-2d771a00-5eaf-11eb-9858-780ffeae3d92.png)
