### ISSUE TITLE
3 level of navigation in header

### ISSUE THREAD

**Issue by ashfahan** [assemblysoft/charity-template#2]
in one of conversation, you said you need header with 3 levels of navigation.

can you explain it more ? maybe some image or anything? so what i better idea of what to create

Requires some more design work

**Comment by assemblysoft** [comment]
Yes, see the header navigation bar image in the document.

**Comment by ashfahan** [comment]
do you want the header bar to be exact same like that ? cuz i followed the sample site design that u gave me and created a creativity bit out of it.

**Comment by assemblysoft** [comment]
It has 3 layers of menu, which is important. It shows the current main menu
selected, a sub menu and drop down menu items. The buttons at the top are
separate. Happy for you to come up with a design that works well together
but the 3 layers are important.

2nd and 3rd layers change on scroll down. See document.

3 buttons at the top are outside of this.

The actual

**Comment by assemblysoft** [comment]
Needs a bit more design work

**Comment by ashfahan** [comment]
Hello @assemblysoft after a deep study of design and the implementation of 3 level of nav. I find it very poor to implement it the design get so complicated and quickly over wheeling with the no of items we put into navigation. to keep the design consistent, i think we should stick with 1 and 2 level of navigation with extra items to be moved into dropdown or mega dropdowns menu like.

![image](https://user-images.githubusercontent.com/19289015/103684043-cb607e80-4fac-11eb-814a-75323720542e.png)
![image](https://user-images.githubusercontent.com/19289015/103684109-da473100-4fac-11eb-943c-9dd2d3c058fd.png)

**Comment by ashfahan** [comment]
if we still need it we might need to implement the design like 


![image](https://user-images.githubusercontent.com/19289015/103684457-66595880-4fad-11eb-8a4a-726fbb38b06b.png)
Centered aligned

![image](https://user-images.githubusercontent.com/19289015/103684595-a1f42280-4fad-11eb-8b16-ccdda175d384.png)
or keep it the way it is with just color and ui improvements

**Comment by assemblysoft** [comment]
Do very similar to this:
![image](https://user-images.githubusercontent.com/1641755/103824863-a2072780-506c-11eb-94a9-63005936c3f8.png)

2nd level can be a mega menu

**Comment by assemblysoft** [comment]
Donate buttons need an icon + text
Donate would be good with a 'paw' icon. Buy rain forest with a 'tree' icon'
Big, bold and colorful, like below:
![image](https://user-images.githubusercontent.com/1641755/103825604-0924dc00-506d-11eb-9738-b88cf6c4bb39.png)

**Comment by assemblysoft** [comment]
Donate
![image](https://user-images.githubusercontent.com/1641755/103825829-7c2e5280-506d-11eb-80b8-7b18c76b4a36.png)
![image](https://user-images.githubusercontent.com/1641755/103825868-8fd9b900-506d-11eb-91b4-70ad92b27408.png)
![image](https://user-images.githubusercontent.com/1641755/103825892-9e27d500-506d-11eb-962c-47a5003c3673.png)

Buy Rain forest
![image](https://user-images.githubusercontent.com/1641755/103825940-bb5ca380-506d-11eb-96c9-0d3554141692.png)

Adopt
![image](https://user-images.githubusercontent.com/1641755/103826113-21492b00-506e-11eb-9d0e-86ac1e1da7a5.png)

**Comment by assemblysoft** [comment]
2nd level dropdown + mega menu example:
https://davidshepherd.org/donate/

**Comment by assemblysoft** [comment]
menu link:
https://www.paigntonzoo.org.uk/plan-your-visit/opening-times

**Comment by assemblysoft** [comment]
@ashfahan, please **focus** on the **menu**, **mega menu**, and **donate button** designs to form an agreed header section.

**Comment by assemblysoft** [comment]
The solid blue colour is not working

**Comment by ashfahan** [comment]
> The solid blue colour is not working

i changed the primary color to orange like so that i gives a touch of earth look. if you have some color suggested do let me know

**Comment by ashfahan** [comment]
> @ashfahan, please **focus** on the **menu**, **mega menu**, and **donate button** designs to form an agreed header section.

i have update the header icons they look alot more nicer than before and regarding the 2nd nav i have implimented the basic nav and will try to improve its futher ui if there is something possible
