### ISSUE TITLE
Cropped donate buttons - Horizontal mobile

### ISSUE THREAD

**Issue by assemblysoft** [assemblysoft/charity-template#29]

**Comment by assemblysoft** [comment]
![image](https://user-images.githubusercontent.com/1641755/109848026-bc621980-7c47-11eb-8498-a9c3f72d40fe.png)

**Comment by ashfahan** [comment]
![image](https://user-images.githubusercontent.com/19289015/110200978-983e4c80-7e82-11eb-84f3-a78c67a9b155.png)
fixed
