### ISSUE TITLE
No paw rollover for cards

### ISSUE THREAD

**Issue by assemblysoft** [assemblysoft/charity-template#30]

**Comment by assemblysoft** [comment]
![image](https://user-images.githubusercontent.com/1641755/109848753-85d8ce80-7c48-11eb-824a-30d056057b86.png)

**Comment by assemblysoft** [comment]
We spoke about a Paw icon rollover with dark overlay for all link items

**Comment by ashfahan** [comment]
![image](https://user-images.githubusercontent.com/19289015/110200888-e6068500-7e81-11eb-87ed-a8bad83ccbc8.png)

which page is it from  ?

**Comment by ashfahan** [comment]
fixed over the adopt page
