### ISSUE TITLE
Donation widget responsive issue

### ISSUE THREAD

**Issue by assemblysoft** [assemblysoft/charity-template#33]

**Comment by assemblysoft** [comment]
![image](https://user-images.githubusercontent.com/1641755/109939423-f293ad80-7cc8-11eb-8815-39c1cbc66271.png)

**Comment by ashfahan** [comment]
![image](https://user-images.githubusercontent.com/19289015/110200301-0b45c400-7e7f-11eb-8c49-7a44356a2771.png)
Updated
