### ISSUE TITLE
Contact form not remdering properly on mobile (portrait) samsung glalxy s25

### ISSUE THREAD

**Issue by assemblysoft** [assemblysoft/charity-template#34]
Fields and text not laid out correctly on contact form fields, labels and text

**Comment by assemblysoft** [comment]
![image](https://user-images.githubusercontent.com/1641755/110250765-167b1b80-7f75-11eb-9488-b633c8a78e2d.png)

**Comment by ashfahan** [comment]
![image](https://user-images.githubusercontent.com/19289015/110333233-2d883f00-8043-11eb-981a-5d410dcc6148.png)
![image](https://user-images.githubusercontent.com/19289015/110333296-3f69e200-8043-11eb-89df-23cc7530eec5.png)

fixed
