### ISSUE TITLE
Homepage 6 - Full page video and Text needs to update

### ISSUE THREAD

**Issue by ashfahan** [assemblysoft/charity-template#4]
There is not text in the image provided

![image](https://user-images.githubusercontent.com/19289015/103159455-627a4900-47eb-11eb-9215-dcacc65bc135.png)

**Comment by assemblysoft** [comment]
It should be a carousel. Combining previous pages.

**Comment by ashfahan** [comment]
wasnt that supposed to be homepage 8 🤔💭 ?

**Comment by assemblysoft** [comment]
Yes you are right. Text can be anything but needs to switch from one tag
line to another.

Please use:
2 second delay
Helping save wild animals
3 second delay
Looking for volunteers
3 second delay
Making a difference to rain forests

**Comment by ashfahan** [comment]
oh got your point, you want the text to update as the video play 👌
