### ISSUE TITLE
Donate Buttons

### ISSUE THREAD

**Issue by assemblysoft** [assemblysoft/charity-template#9]

**Comment by assemblysoft** [comment]
![image](https://user-images.githubusercontent.com/1641755/105167905-3bc0e100-5b11-11eb-819c-7e4483aec5c9.png)

Need to be bigger

**Comment by ashfahan** [comment]
![image](https://user-images.githubusercontent.com/19289015/105642989-f86ac780-5eae-11eb-9ffc-9cff5c5cf983.png)
